### ISSUE TITLE
Show/hide keyboard in landscape mode

### ISSUE THREAD

**Issue by valllllll2000** [tynn-xyz/Hoppa#1]
Not sure if this even qualifies as a bug since this seems to be an issue with the androidx core library but in landscape mode, the show/hide keyboard methods do not get called with apis 23 to 29 (30+ works perfectly). You can see my issue here (not related to your code):

https://stackoverflow.com/questions/69372950/detect-when-a-keyboard-is-shown-hidden-issues-in-android-with-onapplywindowinset

In an attempt to fix it, I decided to try your library and unfortunately the same issue is there. I can provide the sample code if needed.

Also: maybe explain that to show/hide keyboard events need android:windowSoftInputMode="adjustResize" in manifest or it will not work at all for APIs 23-29

**Comment by tynn** [comment]
I guess I've never used or tested a keyboard in landscape mode before. When I did, it showed a fullscreen keyboard only, so all my use-cases worked out well. Evenutally I was able to show the keyboard on an emulator for tablets. Android 30 obviously worked well, while Android 29 seemed to be working fine too. I'm using `androidx.core:core-ktx:1.6.0` with it.

Could your issue be related to the screen size itself?

I used the example app from cda789e046667763291e675db016a6503ba0c323 for testing.
